### ISSUE TITLE
atc demo ui stops working after "vagrant reload trusty"

### ISSUE THREAD

**Issue by jrabek** [facebook/augmented-traffic-control#120] opened 2015-05-22 17:54 UTC
After running "vagrant reload trusty", the demo ui at http://localhost:8080/atc_demo_ui/ is no longer available.  telnetting to the port results in the connection being closed immediately so it seems the port forwarding is still correct but maybe gunicorn is not listening.

**Comment by jrabek** [comment] 2015-05-22 17:55
Running "vagrant destroy trusty" and then "vagrant up trusty" fixes the issue with no other configuration changes.

**Comment by chantra** [comment] 2015-05-25 00:31
@jrabek 
Same here, long weekend so we did not get a chance to look at it yet.

I think the issue with reload is that the shared filesystem does not get mounted. You do not have to destroy the VM, but just stop/start.

Can you reproduce if you:
```
vagrant halt trusty
vagrant up trusty
```
?

**Comment by chantra** [comment] 2015-05-25 01:20
actually, I could quickly give a spin to this on my setup and could not repro. `reload` does properly remount the shares and the atcui.
Could you create a [gist](https://gist.github.com/) with the output of `vagrant reload trusty`

Tks

**Comment by zfjagann** [comment] 2015-05-26 18:33
I've seen this issue before. A quick way to fix this is `vagrant ssh trusty` and then inside the ssh shell `sudo start atcui` (or `sudo restart atcui` if that doesn't work).

**Comment by jrabek** [comment] 2015-05-26 23:45
@chantra.  Here is the output of vagrant reload trusty: https://gist.github.com/jrabek/14a4a4d8a0105a0d292c.  I checked and the demo ui is not accessible via http://localhost:8080 following the reload.

Running the following does not work either:
```
vagrant halt trusty
vagrant up trusty
```
Here is the output from that:https://gist.github.com/jrabek/8248b6e8f5c9c68b2b53

**Comment by jrabek** [comment] 2015-05-26 23:46
@chantra @zfjagann , manually starting the atcui works as @zfjagann suggested.

**Comment by zfjagann** [comment] 2015-05-27 00:20
Our atcui upstart config is set to start after the network interfaces are brought up. I'll be that vagrant is short-cutting the boot process and upstart is not emitting that signal, thus atcui doesn't start up.

Interesting. I'll take a closer look at this and get something working.

**Comment by zfjagann** [comment] 2015-05-27 00:35
I found the problem. Hidden in chef there was a udev rule that restarted `atcui` whenever the vagrant box restarted. Apparently this can't be done with upstart easily (I tried `runlevel` and `started` with various arguments).

**Comment by chantra** [comment] 2015-05-27 06:25
@zfjagann I cant seem to reproduce the problem on my setup. I have been restarting the VM and atcui always came up.

That being said, we should change `/etc/udev/rules.d/50-vagrant-mount-atc{ui,d}.rules` do run whichever is needed based on the underlying init subsystem.

**Comment by zfjagann** [comment] 2015-05-27 21:15
The problem is that the commands they need to run are different now that we switched atcui to use upstart. If you look in syslog you'll see error messages about `/usr/init.d/atcui` not existing. I was half-way through testing a patch to this when I had to leave yesterday, I might be able to get it in today if I have time.

**Comment by chantra** [comment] 2015-06-04 22:51
@jrabek I will be closing this issue for now. You have a workaround that should get you going.
I wish we could have a way to reproduce at will, that would be easier for us to fix this.

**Closed by chantra** 2015-06-04 22:51 UTC
