### ISSUE TITLE
No CSS style in ATC UI demo

### ISSUE THREAD

**Issue by liweijian** [facebook/augmented-traffic-control#217] opened 2015-12-11 08:14 UTC
I was  trying to run the ATC UI demo, when I opened the  http://localhost:8000, I found it's ugly.

I read the source code of the web page, it shows

```html
   <!-- Bootstrap CSS -->
    &lt;link rel=&quot;stylesheet&quot; href=&quot;/static/bootstrap/themes/default/css/bootstrap.min.css&quot; type=&quot;text/css&quot;&gt;
    <!-- Bootstrap JS -->
    &lt;script type=&quot;text/javascript&quot; src=&quot;/static/bootstrap/js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
```

Is there any config I missed?

**Comment by chantra** [comment] 2015-12-11 08:16
@liweijian see #216 the issue is due to the fact that you are running django 1.9 as explained in https://github.com/facebook/augmented-traffic-control/issues/216#issuecomment-163851279

**Comment by chantra** [comment] 2015-12-11 08:20
Closing as duplicate of #216

**Closed by chantra** 2015-12-11 08:20 UTC
