### ISSUE TITLE
change network,but not work.

### ISSUE THREAD

**Issue by DoctorQ** [facebook/augmented-traffic-control#131] opened 2015-07-03 08:10 UTC
I installed atc by [docker-image](https://registry.hub.docker.com/u/atcd/atc/)
then,I try to change network
# step 1

I choose the "No Connectivity"
![d82936732cae9f883412e885fe2e08a0](https://cloud.githubusercontent.com/assets/4489853/8495131/a0d49afe-219d-11e5-8309-51d12b1fa940.jpg)
# step 2
Update Shaping，but not work?
![5ba5630eabf02aa31b1612fd1af45adf](https://cloud.githubusercontent.com/assets/4489853/8495127/98371700-219d-11e5-982e-350daafdef95.jpg)

# Summary

how to change network right?

**Comment by chantra** [comment] 2015-07-04 02:29
@DoctorQ just to make sure, 10.58.37.71 is a gateway for your android device (the machine you are running the docker instance is a router for your android device).
How did you start the docker image? By default eth0 is used as the interface that connects to internet, eth1 as the interface that connect to your local network, is this matching your setup? Did you override the environment variable?

**Comment by chantra** [comment] 2015-07-08 19:38
Hi @DoctorQ is it working for you now? If not, did you get a chance to provide answers to my questions?

**Comment by DoctorQ** [comment] 2015-07-09 04:10
oh,@chantra sorry!I know the reason why not work.My wifi AP is not build.I don't know your docker image if can share Wifi Ap or not.


Yesterday， I setup wifi ap in linux,then use source code env,then success.Answer your questions below:
# How did you start the docker image

`docker run -it --privileged --net=host --rm atcd/atc`

#is this matching your setup

I use docker in OS X 10.10.3,use virturalbox ,ubuntu 14.04.so I don't know my eth0 or eth1,sorry.


otherwise,I can use atc to test my app! I'm newer in docker !I'm learning .Thanks your work.

**Comment by chantra** [comment] 2015-07-09 04:23
@DoctorQ 
So, you will have some work to do on your side to get this working, and we do not support running atc in vagrant (but for developing/testing purpose).
I am not really sure what your set up look like, but supposing that your wifi AP is running on your home router, your traffic will never be  shaped by ATC. ATC `MUST` be routing your packets, which means that ATC is going to be a router that your packets go through when accessing internet.

You are running atc in a docker container in a VM. What you need to do is to make this VM your router and then start ATC and tell it to shape the traffic coming and going out of the interfaces of your VM.

One way you could attempt that is by setting a Wireless AP on your MAC. Then attach the wireless device to your virtualbox VM. You will most likely need to configure DHCP in the VM to provide ips to clients that connect to the AP.
Then, you can start ATC in a docker container within the VM and get it to shape the VM traffic.

I will close this task as this is not an ATC issue, but rather a really complicated set up that can work somehow but not straighforward. ATC is meant to run on a router so you should have a router running linux in the first place.
That being said, I am happy to help you via IRC on #atcd when I am online and in front of a screen.

**Closed by chantra** 2015-07-09 04:23 UTC

**Comment by DoctorQ** [comment] 2015-07-09 04:27
@chantra  I will try to use atc by docker again!because it is easy to setup!Thanks.

**Comment by DoctorQ** [comment] 2015-07-09 04:31
@chantra  Hope you can provider more document about how to setup atc by docker image.

**Comment by chantra** [comment] 2015-07-09 04:39
@DoctorQ 
> @chantra I will try to use atc by docker again!because it is easy to setup!Thanks.

I understand, and this is the reason why there is a docker image, nevertheless your issue at the moment is not about being able to run ATC (which you successfully did), but about making your VM a router for your devices.

Unfortunately, I do not have any documentation handy to provide here. But regardless of ATC, you first need to get your ubuntu VM to route your traffic. Once you have that, your next step will be to run ATC in a docker instance.
So, the problem is not about ATC yet, but about getting your ubuntu VM on your mac to act as a router (which is outside the scope of ATC), once this will be solved, I will be more than happy to help  you getting ATC to run.
