### ISSUE TITLE
Stylesheet issue

### ISSUE THREAD

**Issue by MiteshShah** [facebook/augmented-traffic-control#216] opened 2015-12-10 12:01 UTC
Refer: https://cloud.githubusercontent.com/assets/1223371/11714922/af5ff6a6-9f63-11e5-84d0-a17c2dae1a20.png

![atc](https://cloud.githubusercontent.com/assets/1223371/11714922/af5ff6a6-9f63-11e5-84d0-a17c2dae1a20.png)

**Comment by zfjagann** [comment] 2015-12-10 20:02
Which browser and version are you using?

Do you think you could provide the console log from your browser? (e.g. `Ctrl-Shift-J`/`Cmd-Opt-J` on Chrome)

**Comment by chantra** [comment] 2015-12-10 21:02
Well, the issue is that the `link` resource is not being evaluated see the first line of the screenshot.

Once thing to verify would be if wether the css is available at the given path: /static/bootstrap/themes/default/css/bootstrap.min.css 

It is weird that it did not get rendered anyway. Can you give more details on: what browser you are using, what OS, does that reproduce after a forced refresh (Ctrl-Alt-R)...

**Comment by MiteshShah** [comment] 2015-12-11 05:55
@zfjagann MAC OS El Captain 10.11.2
Gogole Chrome Version 47.0.2526.80 (64-bit)

Dirty Fix:

```
vim ~/dev/atc/venv/lib/python2.7/site-packages/atc_demo_ui/templates/atc_demo_ui/base.html 

# Find and replace follwoing lines
    <!-- Bootstrap CSS -->
    {% bootstrap_styles theme='default' type='min.css' %}
    <!-- Bootstrap JS -->
    {% bootstrap_script use_min=True %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/bootstrap/themes/default/css/bootstrap.min.css" type="text/css">
    <!-- Bootstrap JS -->
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
```

![atc](https://cloud.githubusercontent.com/assets/1223371/11736940/cdaf16aa-9ff9-11e5-920e-1bfd6db3958a.png)

**Comment by chantra** [comment] 2015-12-11 05:59
Seems like the tags from https://github.com/no-dice/django-bootstrap-themes are not being evaluated correctly.
I wonder what the generated html source looked like.

**Comment by harshadyeola** [comment] 2015-12-11 06:02
@MiteshShah :+1:

**Comment by MiteshShah** [comment] 2015-12-11 06:03
@chantra Page Source - http://pastebin.com/1zgahvix

```
 <!-- Bootstrap CSS -->
    &lt;link rel=&quot;stylesheet&quot; href=&quot;/static/bootstrap/themes/default/css/bootstrap.min.css&quot; type=&quot;text/css&quot;&gt;
    <!-- Bootstrap JS -->
    &lt;script type=&quot;text/javascript&quot; src=&quot;/static/bootstrap/js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
```

**Comment by chantra** [comment] 2015-12-11 06:03
@MiteshShah thanks. there is some escaping going on here.... :smile:

**Comment by chantra** [comment] 2015-12-11 06:10
I just tested and it does not repro on django 1.7 and django_bootstrap_theme 3.1.2

https://gist.github.com/chantra/d1bc8e6cc0225e3e0c08

@MiteshShah I would guess you use django 1.9 and https://docs.djangoproject.com/en/1.9/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape is kicking in.

**Comment by chantra** [comment] 2015-12-11 06:23
Could repro on Django 1.9 and opened https://github.com/no-dice/django-bootstrap-themes/issues/2

**Comment by chantra** [comment] 2015-12-11 06:54
@MiteshShah thanks for reporting this. Currently ATC supports Django 1.7 (https://github.com/facebook/augmented-traffic-control/blob/master/Setup.md#python-27-and-pip) while it most likely work with newer django (aside from this ui glitch), we do not support it.

The fix here really is to get the upstream module fixed. In the meantime if you dont want to patch your own version of `base.html`, you can downgrade django to 1.7.

I will close this issue as there is some work arounds and will try to get this addressed upstream.

**Comment by chantra** [comment] 2015-12-11 08:19
I will leave this open a big more given that there were other reports, it is not super explicit that we support django 1.7 (looking at the different docs we have, it is sometime mentioned 1.7 sometimes 1.7+)

**Comment by chantra** [comment] 2015-12-14 02:59
no-dice/django-bootstrap-themes/pull/3 should be addressing this issue.

**Comment by chantra** [comment] 2016-01-07 21:15
https://pypi.python.org/pypi/django-bootstrap-themes/3.1.3 is out there! I will close this task as future should not hit this issue anymore.

**Closed by chantra** 2016-01-07 21:15 UTC
Labels: atc_demo_ui, requirements not met

**Comment by zfjagann** [comment] 2016-01-08 01:07
:confetti_ball: :+1: :confetti_ball: :+1: :facepunch: :confetti_ball:
