### ISSUE TITLE
can not build develop enviroment

### ISSUE THREAD

**Issue by wildpeanut** [facebook/augmented-traffic-control#95] opened 2015-04-12 11:33 UTC
Hello,

error happened after restart service atcd, below is error log and environment info, any advice and suggestions will be greatly appreciated!

===== vagrant version =====
Vagrant 1.7.2

===== vagrant plugin list =====
vagrant-berkshelf (4.0.3)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.3, system)

===== chef version =====
hef Development Kit Version: 0.4.0

===== error log ======

==> trusty: [2015-04-12T11:05:18+00:00] INFO: template[/etc/default/atcd] sending restart action to service[atcd] (delayed)
==> trusty: ================================================================================
==> trusty: Error executing action `restart` on resource 'service[atcd]'
==> trusty: ================================================================================
==> trusty: Errno::ENOENT
==> trusty: -------------
==> trusty: No such file or directory - /etc/init.d/atcd
==> trusty: Resource Declaration:
==> trusty:
==> trusty: ---------------------
==> trusty: # In /tmp/vagrant-chef/ae4cfd0ce0224b28bb18503728431d99/cookbooks/atc/recipes/atcd.rb
==> trusty:
==> trusty: 126: service 'atcd' do
==> trusty: 127:   supports :restart => true
==> trusty: 128:   action [:enable, :start]
==> trusty: 129: end
==> trusty:
==> trusty: Compiled Resource:
==> trusty: ------------------
==> trusty: # Declared in /tmp/vagrant-chef/ae4cfd0ce0224b28bb18503728431d99/cookbooks/atc/recipes/atcd.rb:126:in `from_file'
==> trusty:
==> trusty: service("atcd") do
==> trusty:   action [:enable, :start]
==> trusty:   updated true
==> trusty:   supports {:restart=>true}
==> trusty:   retries 0
==> trusty:   retry_delay 2
==> trusty:   default_guard_interpreter :default
==> trusty:   service_name "atcd"
==> trusty:   enabled true
==> trusty:   pattern "atcd"
==> trusty:   declared_type :service
==> trusty:   cookbook_name :atc
==> trusty:   recipe_name "atcd"
==> trusty: end
==> trusty:
==> trusty: [2015-04-12T11:05:18+00:00] INFO: ruby_block[test-iptables] sending run action to execute[reload-iptables] (delaye
==> trusty: [2015-04-12T11:05:18+00:00] INFO: execute[reload-iptables] ran successfully
==> trusty: [2015-04-12T11:05:18+00:00] ERROR: Running exception handlers
==> trusty: [2015-04-12T11:05:18+00:00] ERROR: Exception handlers complete
==> trusty: [2015-04-12T11:05:18+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> trusty: [2015-04-12T11:05:18+00:00] ERROR: Chef::Exceptions::MultipleFailures
==> trusty: [2015-04-12T11:05:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit
code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by chantra** [comment] 2015-04-12 16:08
@wildpeanut could you give more details on what step you did to trigger this please. 

I can't get to reproduce this from a new vm even when triggering the restart:
```
==> trusty: [2015-04-12T16:02:32+00:00] INFO: template[/etc/default/atcd] sending restart action to service[atcd] (delayed)
==> trusty: [2015-04-12T16:02:32+00:00] INFO: service[atcd] restarted
==> trusty: [2015-04-12T16:02:32+00:00] INFO: Chef Run complete in 45.094454378 seconds
```

**Comment by wildpeanut** [comment] 2015-04-13 01:05
Hello chantra,

thanks for reply, here is another log , I notice the other error happened before

===== log =====

==> trusty: Vendoring yum-epel (0.6.0) to C:/Users/AlinHuang/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150412-9712-ey244e-tr
usty/yum-epel
==> trusty: Clearing any previously set network interfaces...
==> trusty: Preparing network interfaces based on configuration...
    trusty: Adapter 1: nat
    trusty: Adapter 2: hostonly
==> trusty: Forwarding ports...
    trusty: 8000 => 8080 (adapter 1)
    trusty: 22 => 2222 (adapter 1)
==> trusty: Running 'pre-boot' VM customizations...
==> trusty: Booting VM...
==> trusty: Waiting for machine to boot. This may take a few minutes...
    trusty: SSH address: 127.0.0.1:2222
    trusty: SSH username: vagrant
    trusty: SSH auth method: private key
    trusty: Warning: Connection timeout. Retrying...
    trusty:
    trusty: Vagrant insecure key detected. Vagrant will automatically replace
    trusty: this with a newly generated keypair for better security.
    trusty:
    trusty: Inserting generated public key within guest...
    trusty: Removing insecure key from the guest if its present...
    trusty: Key inserted! Disconnecting and reconnecting using new SSH key...
==> trusty: Machine booted and ready!
==> trusty: Checking for guest additions in VM...
==> trusty: Setting hostname...
==> trusty: Configuring and enabling network interfaces...
==> trusty: Mounting shared folders...
    trusty: /vagrant => D:/MyWork/MyStudy/Facebook-ATC/atc/chef/atc
    trusty: /usr/local/src/atc/atc => D:/MyWork/MyStudy/Facebook-ATC/atc/atc
    trusty: /tmp/vagrant-chef/ae4cfd0ce0224b28bb18503728431d99/cookbooks => C:/Users/AlinHuang/.berkshelf/vagrant-berkshelf/shelve
s/berkshelf20150412-9712-ey244e-trusty
==> trusty: Installing Chef 12.2.1 Omnibus package...

==> trusty: Downloading Chef 12.2.1 for ubuntu...
==> trusty: downloading https://www.getchef.com/chef/metadata?v=12.2.1&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64

==> trusty:   to file /tmp/install.sh.1594/metadata.txt
==> trusty: trying wget...
==> trusty: url https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_12.2.1-1_amd64.deb
==> trusty: md5 84119f54115d754373c9891b8759497c
==> trusty: sha256      8e0a8a2477c11615f86ffe686a68fa6636112ba82ebe6bb22daa5dd416f3c13e
==> trusty: downloaded metadata file looks valid...
==> trusty: downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_12.2.1-1_amd64.deb
==> trusty:   to file /tmp/install.sh.1594/chef_12.2.1-1_amd64.deb
==> trusty: trying wget...
==> trusty: Comparing checksum with sha256sum...
==> trusty: Installing Chef 12.2.1
==> trusty: installing with dpkg...
==> trusty: Selecting previously unselected package chef.
==> trusty: (Reading database ... 32400 files and directories currently installed.)
==> trusty: Preparing to unpack .../chef_12.2.1-1_amd64.deb ...
==> trusty: Unpacking chef (12.2.1-1) ...
==> trusty: Setting up chef (12.2.1-1) ...
==> trusty: Thank you for installing Chef!
==> trusty: Running provisioner: chef_solo...
==> trusty: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> trusty: Running chef-solo...
==> trusty: stdin: is not a tty
==> trusty: [2015-04-12T10:54:36+00:00] INFO: Forking chef instance to converge...
==> trusty: [2015-04-12T10:54:36+00:00] INFO: *** Chef 12.2.1 ***
==> trusty: [2015-04-12T10:54:36+00:00] INFO: Chef-client pid: 1749
==> trusty: [2015-04-12T10:54:44+00:00] INFO: Setting the run_list to ["recipe[python]", "recipe[atc::default]"] from CLI options
==> trusty: [2015-04-12T10:54:44+00:00] INFO: Run List is [recipe[python], recipe[atc::default]]
==> trusty: [2015-04-12T10:54:44+00:00] INFO: Run List expands to [python, atc::default]
==> trusty: [2015-04-12T10:54:44+00:00] INFO: Starting Chef Run for trusty
==> trusty: [2015-04-12T10:54:44+00:00] INFO: Running start handlers
==> trusty: [2015-04-12T10:54:44+00:00] INFO: Start handlers complete.
==> trusty: [2015-04-12T10:54:46+00:00] INFO: Dhcp Peer:
==> trusty: [2015-04-12T10:54:46+00:00] INFO: Attribute node[:dhcp][:networks] is empty, guess you are using LWRP
==> trusty: [2015-04-12T11:01:40+00:00] INFO: apt_package[python-dev] installed python-dev at 2.7.5-5ubuntu3


==> trusty: [2015-04-12T11:01:40+00:00] INFO: cookbook_file[/var/chef/cache/get-pip.py] created file /var/chef/cache/get-pip.py
==> trusty: [2015-04-12T11:01:40+00:00] INFO: cookbook_file[/var/chef/cache/get-pip.py] updated file contents /var/chef/cache/get-
pip.py
==> trusty: [2015-04-12T11:01:40+00:00] INFO: cookbook_file[/var/chef/cache/get-pip.py] mode changed to 644
==> trusty: [2015-04-12T11:01:57+00:00] INFO: execute[install-pip] ran successfully
==> trusty: [2015-04-12T11:02:04+00:00] INFO: Upgrading python_pip[setuptools] version from 15.0 to latest
==> trusty: [2015-04-12T11:02:11+00:00] INFO: Upgrading python_pip[virtualenv] version from uninstalled to latest
==> trusty: [2015-04-12T11:02:24+00:00] INFO: group[atc] created
==> trusty: [2015-04-12T11:02:25+00:00] INFO: user[atc] created
==> trusty: [2015-04-12T11:03:23+00:00] INFO: execute[apt-get update] ran successfully
==> trusty: [2015-04-12T11:04:27+00:00] INFO: apt_package[git] installed git at 1:1.9.1-1ubuntu0.1
==> trusty: [2015-04-12T11:04:27+00:00] INFO: directory[/usr/local/atc] created directory /usr/local/atc
==> trusty: [2015-04-12T11:04:27+00:00] INFO: directory[/usr/local/atc] owner changed to 1000
==> trusty: [2015-04-12T11:04:27+00:00] INFO: directory[/usr/local/atc] group changed to 1000
==> trusty: [2015-04-12T11:04:27+00:00] INFO: directory[/usr/local/atc] mode changed to 755
==> trusty: [2015-04-12T11:04:27+00:00] INFO: link[/usr/atc] created
==> trusty: [2015-04-12T11:04:27+00:00] INFO: Creating virtualenv python_virtualenv[/usr/local/atc/venv] at /usr/local/atc/venv
==> trusty: [2015-04-12T11:04:27+00:00] INFO: directory[/usr/local/atc/venv] created directory /usr/local/atc/venv
==> trusty: [2015-04-12T11:04:27+00:00] INFO: directory[/usr/local/atc/venv] owner changed to 1000
==> trusty: [2015-04-12T11:04:27+00:00] INFO: directory[/usr/local/atc/venv] group changed to 1000
==> trusty: [2015-04-12T11:04:29+00:00] INFO: execute[virtualenv --python=python2.7  /usr/local/atc/venv] ran successfully
==> trusty: [2015-04-12T11:04:29+00:00] INFO: Using interfaces lan=>eth1, wan=>eth0
==> trusty: [2015-04-12T11:04:29+00:00] INFO: ruby_block[run-iptables-resources-early] called
==> trusty: [2015-04-12T11:04:30+00:00] INFO: template[/etc/iptables-rules] created file /etc/iptables-rules
==> trusty: [2015-04-12T11:04:30+00:00] INFO: template[/etc/iptables-rules] updated file contents /etc/iptables-rules
==> trusty: [2015-04-12T11:04:30+00:00] INFO: file[/etc/network/if-up.d/iptables-rules] created file /etc/network/if-up.d/iptables
-rules
==> trusty: [2015-04-12T11:04:30+00:00] INFO: file[/etc/network/if-up.d/iptables-rules] updated file contents /etc/network/if-up.d
/iptables-rules
==> trusty: [2015-04-12T11:04:30+00:00] INFO: file[/etc/network/if-up.d/iptables-rules] owner changed to 0
==> trusty: [2015-04-12T11:04:30+00:00] INFO: file[/etc/network/if-up.d/iptables-rules] group changed to 0
==> trusty: [2015-04-12T11:04:30+00:00] INFO: file[/etc/network/if-up.d/iptables-rules] mode changed to 755
==> trusty: [2015-04-12T11:04:50+00:00] INFO: apt_package[isc-dhcp-server] installed isc-dhcp-server at 4.2.4-7ubuntu12
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/default/isc-dhcp-server] backed up to /var/chef/backup/etc/default/isc
-dhcp-server.chef-20150412110450.861539
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/default/isc-dhcp-server] updated file contents /etc/default/isc-dhcp-s
erver
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/dhcpd.conf] backed up to /var/chef/backup/etc/dhcp/dhcpd.conf.che
f-20150412110450.881140
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/dhcpd.conf] updated file contents /etc/dhcp/dhcpd.conf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: directory[/etc/dhcp/groups.d] created directory /etc/dhcp/groups.d
==> trusty: [2015-04-12T11:04:50+00:00] INFO: file[/etc/dhcp/groups.d/list.conf] created file /etc/dhcp/groups.d/list.conf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: file[/etc/dhcp/groups.d/list.conf] updated file contents /etc/dhcp/groups.d/list.con
f
==> trusty: [2015-04-12T11:04:50+00:00] INFO: directory[/etc/dhcp/hosts.d] created directory /etc/dhcp/hosts.d
==> trusty: [2015-04-12T11:04:50+00:00] INFO: file[/etc/dhcp/hosts.d/list.conf] created file /etc/dhcp/hosts.d/list.conf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: file[/etc/dhcp/hosts.d/list.conf] updated file contents /etc/dhcp/hosts.d/list.conf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: directory[/etc/dhcp/subnets.d] created directory /etc/dhcp/subnets.d
==> trusty: [2015-04-12T11:04:50+00:00] INFO: file[/etc/dhcp/subnets.d/list.conf] created file /etc/dhcp/subnets.d/list.conf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: file[/etc/dhcp/subnets.d/list.conf] updated file contents /etc/dhcp/subnets.d/list.c
onf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/100.64.33.0.conf] created file /etc/dhcp/subnets.d/100.
64.33.0.conf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/100.64.33.0.conf] updated file contents /etc/dhcp/subne
ts.d/100.64.33.0.conf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/100.64.33.0.conf] owner changed to 0
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/100.64.33.0.conf] group changed to 0
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/100.64.33.0.conf] mode changed to 644
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/100.64.33.0.conf] not queuing delayed action restart on
 service[isc-dhcp-server] (delayed), as it's already been queued
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/list.conf] backed up to /var/chef/backup/etc/dhcp/subne
ts.d/list.conf.chef-20150412110450.937746
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/list.conf] updated file contents /etc/dhcp/subnets.d/li
st.conf
==> trusty: [2015-04-12T11:04:50+00:00] INFO: template[/etc/dhcp/subnets.d/list.conf] not queuing delayed action restart on servic
e[isc-dhcp-server] (delayed), as it's already been queued
==> trusty: [2015-04-12T11:04:51+00:00] INFO: template[/etc/udev/rules.d/50-vagrant-mount-atcd.rules] created file /etc/udev/rules
.d/50-vagrant-mount-atcd.rules
==> trusty: [2015-04-12T11:04:51+00:00] INFO: template[/etc/udev/rules.d/50-vagrant-mount-atcd.rules] updated file contents /etc/u
dev/rules.d/50-vagrant-mount-atcd.rules
==> trusty: [2015-04-12T11:04:51+00:00] INFO: template[/etc/udev/rules.d/50-vagrant-mount-atcd.rules] updated file contents /etc/u
dev/rules.d/50-vagrant-mount-atcd.rules
==> trusty: [2015-04-12T11:04:51+00:00] INFO: ruby_block[notify-apply-sysctl-params] called
==> trusty: [2015-04-12T11:04:51+00:00] INFO: ruby_block[notify-apply-sysctl-params] sending run action to ruby_block[apply-sysctl
-params] (immediate)
==> trusty: [2015-04-12T11:04:51+00:00] INFO: ruby_block[apply-sysctl-params] called
==> trusty: [2015-04-12T11:04:51+00:00] INFO: ruby_block[apply-sysctl-params] sending create action to template[/etc/sysctl.d/99-c
hef-attributes.conf] (immediate)
==> trusty: [2015-04-12T11:04:51+00:00] INFO: template[/etc/sysctl.d/99-chef-attributes.conf] created file /etc/sysctl.d/99-chef-a
ttributes.conf
==> trusty: [2015-04-12T11:04:51+00:00] INFO: template[/etc/sysctl.d/99-chef-attributes.conf] updated file contents /etc/sysctl.d/
99-chef-attributes.conf
==> trusty: [2015-04-12T11:04:51+00:00] INFO: template[/etc/sysctl.d/99-chef-attributes.conf] mode changed to 644
==> trusty: [2015-04-12T11:04:51+00:00] INFO: template[/etc/sysctl.d/99-chef-attributes.conf] sending start action to service[proc
ps] (immediate)
==> trusty: [2015-04-12T11:04:51+00:00] INFO: service[procps] started
==> trusty: [2015-04-12T11:04:52+00:00] INFO: Installing python_pip[file:///usr/local/src/atc/atc/atc_thrift/] version latest
==> trusty: [2015-04-12T11:05:02+00:00] INFO: Installing python_pip[file:///usr/local/src/atc/atc/atcd/] version latest
==> trusty: [2015-04-12T11:05:17+00:00] INFO: directory[/var/lib/atc] created directory /var/lib/atc
==> trusty: [2015-04-12T11:05:17+00:00] INFO: directory[/var/lib/atc] owner changed to 0
==> trusty: [2015-04-12T11:05:17+00:00] INFO: directory[/var/lib/atc] group changed to 0
==> trusty: [2015-04-12T11:05:17+00:00] INFO: directory[/var/lib/atc] mode changed to 755
==> trusty: [2015-04-12T11:05:17+00:00] INFO: template[/etc/default/atcd] created file /etc/default/atcd
==> trusty: [2015-04-12T11:05:17+00:00] INFO: template[/etc/default/atcd] updated file contents /etc/default/atcd
==> trusty: [2015-04-12T11:05:17+00:00] INFO: template[/etc/default/atcd] owner changed to 0
==> trusty: [2015-04-12T11:05:17+00:00] INFO: template[/etc/default/atcd] group changed to 0
==> trusty: [2015-04-12T11:05:17+00:00] INFO: template[/etc/default/atcd] mode changed to 755
==> trusty: [2015-04-12T11:05:17+00:00] INFO: cookbook_file[/etc/init.d/atcd] created file /etc/init.d/atcd
==> trusty: [2015-04-12T11:05:17+00:00] INFO: cookbook_file[/etc/init.d/atcd] updated file contents /etc/init.d/atcd
==> trusty: [2015-04-12T11:05:17+00:00] INFO: cookbook_file[/etc/init.d/atcd] owner changed to 0
==> trusty: [2015-04-12T11:05:17+00:00] INFO: cookbook_file[/etc/init.d/atcd] group changed to 0
==> trusty: [2015-04-12T11:05:17+00:00] INFO: cookbook_file[/etc/init.d/atcd] mode changed to 755
==> trusty: [2015-04-12T11:05:17+00:00] INFO: cookbook_file[/etc/init.d/atcd] not queuing delayed action restart on service[atcd]
(delayed), as it's already been queued
==> trusty: [2015-04-12T11:05:17+00:00] INFO: service[atcd] enabled
==> trusty: ================================================================================
==> trusty: Error executing action `start` on resource 'service[atcd]'
==> trusty: ================================================================================
==> trusty: Errno::ENOENT
==> trusty: -------------
==> trusty: No such file or directory - /etc/init.d/atcd
==> trusty:
==> trusty:
==> trusty: Resource Declaration:
==> trusty: ---------------------
==> trusty: # In /tmp/vagrant-chef/ae4cfd0ce0224b28bb18503728431d99/cookbooks/atc/recipes/atcd.rb
==> trusty:
==> trusty: 126: service 'atcd' do
==> trusty: 127:   supports :restart => true
==> trusty: 128:   action [:enable, :start]
==> trusty: 129: end
==> trusty:
==> trusty: Compiled Resource:
==> trusty: ------------------
==> trusty: # Declared in /tmp/vagrant-chef/ae4cfd0ce0224b28bb18503728431d99/cookbooks/atc/recipes/atcd.rb:126:in `from_file'
==> trusty:
==> trusty: service("atcd") do
==> trusty:   action [:enable, :start]
==> trusty:   updated true
==> trusty:   supports {:restart=>true}
==> trusty:   retries 0
==> trusty:   retry_delay 2
==> trusty:   default_guard_interpreter :default
==> trusty:   service_name "atcd"
==> trusty:   enabled true
==> trusty:   pattern "atcd"
==> trusty:   declared_type :service
==> trusty:   cookbook_name :atc
==> trusty:   recipe_name "atcd"
==> trusty: end
==> trusty:
==> trusty: [2015-04-12T11:05:17+00:00] INFO: Running queued delayed notifications before re-raising exception

==> trusty: [2015-04-12T11:05:17+00:00] INFO: template[/etc/iptables-rules] sending create action to ruby_block[test-iptables] (de
layed)
==> trusty: [2015-04-12T11:05:18+00:00] INFO: ruby_block[test-iptables] called
==> trusty: [2015-04-12T11:05:18+00:00] INFO: template[/etc/dhcp/dhcpd.conf] sending restart action to service[isc-dhcp-server] (d
elayed)
==> trusty: [2015-04-12T11:05:18+00:00] INFO: service[isc-dhcp-server] restarted
==> trusty: [2015-04-12T11:05:18+00:00] INFO: template[/etc/default/atcd] sending restart action to service[atcd] (delayed)

**Comment by chantra** [comment] 2015-04-15 18:08
@wildpeanut so you are hitting this issue even on a brand new setup. The puzzling part here is that the error says:
```
No such file or directory - /etc/init.d/atcd
```
but the logs shows that file was created just before.

If you ssh in the host, is the file there? Can you run:
```
sudo /etc/init.d/atcd restart
```
?

I still havent been able to repro this, making it somewhat hard to diagnostise.

**Comment by chantra** [comment] 2015-04-15 18:20
Ok, so I have literally nuked the  VM, deleted the box from vagrant cache and the issue is not reproducing for me.
Can you start re-provisioning from scratch?
```
vagrant destroy trusty
vagrant up trusty
```
Does it repro?

FWIW, here is my setup:
vagrant-berkshelf (4.0.2)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.4, system)

vagrant version  1.6.5
chef version that get installed by omnibus: Chef 12.2.1

**Comment by zfjagann** [comment] 2015-04-16 21:22
I've seen a lot filesystem issues (files and dirs going missing) when trying to reprovision an existing vagrant vm. I've never had these issues before with vagrant, so I'm pretty sure it's something related to our chef provisioning, but I haven't had a chance to dig into it. It looks related.

**Comment by chantra** [comment] 2015-04-16 21:23
Hum, it never happened to me...... so I tend to believe it is not an issue with the provisioning :)

**Comment by chantra** [comment] 2015-04-27 03:54
@wildpeanut I am checking if you have any update on this task. Is the issue still happening?
Is `/etc/init.d/atcd` on the hosts? Can you run
```
sudo /etc/init.d/atcd restart
```
Manually? Does this work?

**Comment by chantra** [comment] 2015-04-28 19:49
@wildpeanut did you get a chance to check if the file existed in the VM, could you restart the service using:
```
sudo /etc/init.d/atcd restart
```

I am afraid at this stage I don't have any ways to reproduce the issue.

**Comment by chantra** [comment] 2015-04-30 19:34
@wildpeanut 

I did not get any updates from your side. I have not been able to reproduce this issue so it is not much I can do for now. I will close this task for now. If you can reproduce the issue still, please provide the results to the test I have asked you earlier.
Tks

**Closed by chantra** 2015-04-30 19:34 UTC

**Comment by wildpeanut** [comment] 2015-05-22 05:53
Hello chantra,

I found the reason, the script /etc/init.d/atcd is not properly end in each line. Each line end with ^M.
I remove ^M and resolve this issue.
