### ISSUE TITLE
ImportError when run the atcd

### ISSUE THREAD

**Issue by jinkerry** [facebook/augmented-traffic-control#74] opened 2015-03-26 15:37 UTC
Hi, zeal

When i run the atcd in shell, catch the exception. 
```
jinfengdeMacBook-Pro:atcui jinfeng$ atcd
Traceback (most recent call last):
  File "/usr/local/bin/atcd", line 12, in <module>
    from atcd.scripts import runner
  File "/Library/Python/2.7/site-packages/atcd/scripts/runner.py", line 19, in <module>
    from atcd.AtcdDeviceTimeoutTask import AtcdDeviceTimeoutTask
  File "/Library/Python/2.7/site-packages/atcd/AtcdDeviceTimeoutTask.py", line 10, in <module>
    from atcd.AtcdThriftHandlerTask import AtcdThriftHandlerTask
  File "/Library/Python/2.7/site-packages/atcd/AtcdThriftHandlerTask.py", line 41, in <module>
    from atcd.AtcdDBQueueTask import AtcdDBQueueTask
  File "/Library/Python/2.7/site-packages/atcd/AtcdDBQueueTask.py", line 13, in <module>
    from sparts.tasks.queue import QueueTask
  File "/Library/Python/2.7/site-packages/sparts/tasks/queue.py", line 10, in <module>
    from sparts.collections import PriorityQueue, UniqueQueue
  File "/Library/Python/2.7/site-packages/sparts/collections.py", line 3, in <module>
    from six.moves.queue import Queue
ImportError: No module named queue
```

Thank you

**Comment by chantra** [comment] 2015-03-26 16:32
@jinkerry 
Can you provide the output of:
`pip freeze`
It looks like version of `six` you are using does not have the `queue` module.

As an example, here is the version we have on a working instance:
`six==1.8.0`

**Comment by jinkerry** [comment] 2015-03-27 07:56
Six version is 1.9.0 in my env.
Maybe some other reason?

Thank you.
```
jinfengdeMacBook-Pro:~ jinfeng$ pip freeze
altgraph==0.10.2
atc-thrift==0.1.0
atcd==0.1.0
bdist-mpkg==0.5.0
bonjour-py==0.3
daemonize==2.3.1
Django==1.7.7
django-atc-api==0.1.0
django-atc-demo-ui==0.1.0
django-atc-profile-storage==0.1.0
django-bootstrap-themes==3.1.2
django-static-jquery==1.11.1
djangorestframework==3.1.1
futures==2.2.0
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
py2app==0.7.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyotp==1.4.1
pyparsing==2.0.1
pyroute2==0.3.3
python-dateutil==1.5
pytz==2013.7
scipy==0.13.0b1
six==1.9.0
sparts==0.7.1
thrift==0.9.2
Twisted==13.2.0
xattr==0.6.4
zope.interface==4.1.1
```

**Comment by chantra** [comment] 2015-03-28 01:05
So, looking at your output, there is one thing that will not work even after this issue is fixed: ATC does not run on anything other than Linux.

Aside from that, I have installed on a Mac host a brand new virtualenv with python 2.7.6, installed atcd and six==1.9.0 and cannot reproduce  the issue when importing:
```
from atcd.scripts import runner
```
or running `atcd`

Anyway, I will close this one for now as this is happening on a platform that is not supported. Thanks for reporting the issue in the first place though.

**Closed by chantra** 2015-03-28 01:05 UTC
Labels: invalid

**Comment by zhangxiaang** [comment] 2015-07-19 09:26
i also meet this problem ...my pip free log is:
altgraph==0.10.2
atc-thrift==0.1.2
atcd==0.1.2
bdist-mpkg==0.5.0
bonjour-py==0.3
daemonize==2.3.1
Django==1.8.3
django-atc-api==0.1.2
django-atc-demo-ui==0.1.2
django-atc-profile-storage==0.1.2
django-bootstrap-themes==3.1.2
django-static-jquery==1.11.1
djangorestframework==3.1.3
futures==3.0.3
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
py2app==0.7.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyotp==1.4.1
pyparsing==2.0.1
pyroute2==0.3.3
python-dateutil==1.5
pytz==2013.7
scipy==0.13.0b1
six==1.4.1
sparts==0.7.1
thrift==0.9.2
Twisted==13.2.0
vboxapi==1.0
xattr==0.6.4
zope.interface==4.1.1


how can i resolve this problem or how to update the 'six' version ?
thank u very much!!!

**Comment by chantra** [comment] 2015-07-20 04:43
@zhangxiaang  I understand your issue is fixed given you comment in sparts repo: https://github.com/facebook/sparts/issues/96#issuecomment-122643990
Is this correct?

**Comment by zhangxiaang** [comment] 2015-07-21 02:25
@chantra 
but i meet the same problem with @jinkerry ...
if i import runner , the terminal told me that ImportError: No module named queue...
have u resolved this problem? @jinkerry 
thanks a lot !

**Comment by chantra** [comment] 2015-07-21 04:01
@zhangxiaang 
Do you use virtualenv? When you import runner, do you do this as root? as a normal user?

Can you run:
```
/usr/bin/env python -c 'import six; print six.__version__'
```
and paste the output to https://gist.github.com/

**Comment by zhangxiaang** [comment] 2015-07-21 06:49
@chantra thanks for ur reply!
when i run (as root)

      /usr/bin/env python -c 'import six; print six.__version__'

the output is '1.4.1'
it is strange, when i run " sudo pip freeze" , the six version is 'six==1.9.0'

**Comment by chantra** [comment] 2015-07-21 17:02
@zhangxiaang you may be most likely using a virtualenv setup. You can either start atcd using `sudo` OR make sure you upgrade `six` package for root.
