### ISSUE TITLE
Provide simplified instructions for deploying to DD-WRT/OpenWRT

### ISSUE THREAD

**Issue by jasta** [facebook/augmented-traffic-control#54] opened 2015-03-24 03:33 UTC
I estimate that a large number of users are looking for a simpler set of deployment steps, in particular for deployment to other easy-to-use router firmwares like DD-WRT and OpenWRT.  It would be great to provide a comprehensive guide or a set of simple scripts that automate deployment to these targets.

Additionally, it might even be appropriate to deploy atc to the opkg/ipkg repositories maintained by each of these firmwares, allowing for a simple "opkg install atc" type distribution.  This would give folks new to embedded router firmware a convenient route to get started with cheap hardware.

**Comment by ayufan** [comment] 2015-03-24 16:33
You can try https://github.com/Polidea/Cellular-Data-Network-Simulator :)

**Comment by zfjagann** [comment] 2015-03-24 18:08
I haven't really really given much thought to deploying ATC on DD-WRT/OpenWRT boxes, although I agree it would be useful. @chantra will have better insight into how difficult the iptables/tc integration with these systems will be.

**Comment by chantra** [comment] 2015-03-24 18:52
:) @ayufan Nice! Too bad I did not run into it before. Looking at the timeline, we had  already started our hack sessions on `ATC` and our first versions of `ATC` were pretty close to your solution.

The issue is not going to be iptables/tc as this is already included in the WRTs. I have actually little to no experience with WRTs, but the biggest issue is most likely going to get the whole python stack in. I am not even sure WRT ships the python interpreter by default.

Anyway, this is something that is definitely worth checking.

**Comment by jasta** [comment] 2015-03-24 20:28
Looking at this a little closer, what would the distribution breakdown look like in your view?  The way I see it is that you'd need at least two separate core packages, with maybe one meta package that binds them for convenience:

```
- atc (meta package)
  - atcd
    - atc_thrift
    - python
    - ?
  - atcui (includes django-atc-demo-ui, django-atc-api, django-atc-profile-storage)
    - atc_thrift
    - python
    - django
    - ?
  - atc_thrift
    - python
    - thrift
```

Would this be an accurate breakdown?

**Comment by chantra** [comment] 2015-03-24 23:00
@jasta yes that seem right.

**Comment by jrabek** [comment] 2015-05-28 00:26
@chantra @zfjagann, have either of you gotten feedback about folks setting up ATC on a small form factor device (e.g. https://store.pfsense.org/SG2220, although you would need to install Linux first for thsi one)?  This would allow for a portable traffic shaping appliance like @jasta is interested in.

There are numerous cheap small form factor devices that could work.  Another example:
http://www.alibaba.com/product-detail/Factory-price-hot-selling-ubuntu-mini_60190429796.html

Since the device would be both the access point and the traffic shaper, ATC would need to play well with something like hostapd (https://w1.fi/hostapd/).  Do you think atcd would play well with hostapd?

Have you heard of any setups like this?

**Comment by chantra** [comment] 2015-05-28 00:31
@jrabek most people have installed it on Linux bare metal or Linux VM as far as I can tell.

ATC really just need to have 2 interfaces to shape on, it does not have to interfere/work with hostapd aside from being started after hostapd has set up the wlan interface.

**Comment by jrabek** [comment] 2015-05-28 00:36
@chantra, thanks for the info.  This would still be installing on Linux bare metal, but on an appliance that would serve as the access point as well.  I'll try it out and report back at some point in the future.

**Comment by zfjagann** [comment] 2015-11-10 20:37
I'm going to close this issue since it hasn't been updated since May. Please reopen if you still need help. Thanks!

**Closed by zfjagann** 2015-11-10 20:37 UTC
