### ISSUE TITLE
missing import  patterns function 

### ISSUE THREAD

**Issue by Isor** [facebook/augmented-traffic-control#277] opened 2016-07-01 08:09 UTC
# atcui/urls.py

from django.conf.urls import patterns

urlpatterns = patterns('',
    #...
    # Django ATC API
    url(r'^api/v1/', include('atc_api.urls')),
    # Django ATC Demo UI
    url(r'^atc_demo_ui/', include('atc_demo_ui.urls')),
    # Django ATC profile storage
    url(r'^api/v1/profiles/', include('atc_profile_storage.urls')),
    url(r'^$', RedirectView.as_view(url='/atc_demo_ui/', permanent=False)),
)

**Comment by chantra** [comment] 2016-07-01 15:29
@lsor when setting the project with django, some boilerplate. Isn't it the case anymore?
What version of django are you using?
Cc @smorad

**Comment by chantra** [comment] 2016-07-04 22:31
This is due to using django > 1.7

Django 1.9.7 will create a `urls.py` file like:
```python
"""atcui URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]
```

**Comment by chantra** [comment] 2016-07-22 22:45
@Isor can you confirm what exact version of django you are using please.
Also, what is the exact error, a trace would help.
tks

**Comment by chantra** [comment] 2016-08-08 22:12
@Isor I did not manage to reproduce the issue. I will close this issue now, if this is still an issue for you, please provide more details as to what the issue is.

**Closed by chantra** 2016-08-08 22:12 UTC
