### ISSUE TITLE
 when I use a mobile phone to access url , load image error, respone 404

### ISSUE THREAD

**Issue by FzuLiWei** [facebook/augmented-traffic-control#121] opened 2015-05-25 07:59 UTC
hello, I deploy on linux successfully,I access url from pc work well,but when I use a mobile phone to access begin problem. Look at this:
![image](https://cloud.githubusercontent.com/assets/7477767/7793846/de06b65c-02f6-11e5-9269-e29348417887.png)
![2015 525_155855](https://cloud.githubusercontent.com/assets/7477767/7793850/eef67a24-02f6-11e5-96cc-6bcbd1dc8e0d.png)

please help me!

**Comment by FzuLiWei** [comment] 2015-05-25 08:03
I use VMware Player ,ubuntu 12.0.4

**Comment by zfjagann** [comment] 2015-05-26 18:32
@FzuLiWei What type of mobile phone are you using this on? I've tested the UI on both relatively modern Android and iOS mobile phones, and haven't had any issues like that.

**Comment by chantra** [comment] 2015-05-26 20:58
There used to be task where it did not work on some specific iOS version.can't look for the task now but it may be related.


-------- Original message --------

**Comment by zfjagann** [comment] 2015-05-26 21:00
The screenshot doesn't look like an iOS device to me, but it doesn't look like android 4.0 or 5.0 either.

**Comment by chantra** [comment] 2015-05-27 00:55
Yeah, now that I looked at the screenshot.... it is definitely not iOS :)

From the server logs, it looks like none of the .css or .js files are pulled from the server.

Also, we know it is working on django 1.7, while django 1.8 should work, it has not been tested yet. Can you try to reproduce the issue on django 1.7 please?

This issue feel pretty much related to what was brought up in IRC:  https://gist.github.com/chantra/a99289ee5a432e5a3cc3

**Comment by chantra** [comment] 2015-06-01 19:01
Catching up on this one. The 404 error is ok as from the screenshot, it only affects the favicon.ico

It would be useful to get more info here:
- Is using django 1.7 fixing your issue?
- Can you get some debugging logs (maybe using https://developer.chrome.com/devtools/docs/remote-debugging ), I would like to see where JS is failing.
- What OS version/Browser are you using?

**Comment by chantra** [comment] 2015-06-04 22:39
@FzuLiWei I will close this task for now. If you still see the issue with django 1.7 and can provide the information I was requesting earlier, please feel free to open a new task and we will try to find the cause and a solution.

**Closed by chantra** 2015-06-04 22:39 UTC
Labels: atc_demo_ui, bug

**Comment by chantra** [comment] 2015-06-16 22:48
pinging this issue as it should be fixed as explained in #126
