### ISSUE TITLE
my phone could not load the UI completely

### ISSUE THREAD

**Issue by genius15** [facebook/augmented-traffic-control#126] opened 2015-06-08 13:16 UTC
I have configued the atc and run successfully
but the browser in my android phone can not load the ui completely,I can only see the title "Augmented Traffic COntrol Demo Ui".the browser in my linux can load it correctly. 
I have little knowledage about django ,coule anyone tell me what should I do?

In my own webview ,it throw exception, "ATC is not defined"
![screenshot_2015-06-08-21-14-31](https://cloud.githubusercontent.com/assets/5238926/8035475/a273776e-0e23-11e5-8606-3336ad51c385.png)

**Comment by chantra** [comment] 2015-06-09 02:11
Hi @genius15 

Thanks for reporting this. It seems to be related to #102 and #121 but we have not been able to reproduce it so far.
Can you let us know what:
- android version
- browser
- browser version you are running

Can you reproduce on Android on all browsers? or only some of them.

Could you try to get more detailled logs by doing some remote debugging:  https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by genius15** [comment] 2015-06-09 07:50
hi,@chantra  
I tried a nexus 5 and nexus 6 again，and they can load completely.
yestoday,the phones that can not load correctly are android 4.3、android 4.4.2,I think it may be the google framework is the cause,for the phones's manufacturers are huawei and coolpad,and the manufacturers had removed the google framework in their ROMs.
I debug a test webview which loads the atcui and the log is 
![image](https://cloud.githubusercontent.com/assets/5238926/8053012/3a6d4ee6-0ebf-11e5-8aac-8a969ababb7b.png)

**Comment by chantra** [comment] 2015-06-10 04:32
Thanks @genius15 

this is exactly the same error than in #102 
I will try to reproduce with some variant of android.

**Comment by chantra** [comment] 2015-06-11 04:27
I wonder if moving to JS instead of JSX would solve the problem.

@genius15 could you try to transform the jsx file using https://facebook.github.io/react/docs/tooling-integration.html#jsx  and see if that fixes it.

**Comment by ankit-ankuagrawal** [comment] 2015-06-15 19:09
android: 4.1.1 same problem with crome browser
![device-2015-06-16-003708](https://cloud.githubusercontent.com/assets/11455759/8168077/21982a02-13c0-11e5-8d44-462bcebeb3fc.png)

**Comment by chantra** [comment] 2015-06-16 20:59
@ankit-ankuagrawal @genius15 could you try to use https://github.com/chantra/augmented-traffic-control/tree/fix_old_devices

and confirm it works for you?

**Comment by ankit-ankuagrawal** [comment] 2015-06-16 21:23
@chantra will check ty for ur response

**Comment by chantra** [comment] 2015-06-16 21:52
For posterity.... I was able to reproduce on an emulated nexus one, and `adb logcat` showed:

```
E/browser (  534): Console: TypeError: Result of expression 'a.createElement.bind' [undefined] is not a function. http://localhost:8000/static/vendor/react/react-0.12.2.min.js:14
W/browser (  534): Console: You are using the in-browser JSX transformer. Be sure to precompile your JSX for production - http://facebook.github.io/react/docs/tooling-integration.html#jsx http://localhost:8000/static/vendor/react/JSXTransformer-0.12.2.js:321
E/browser (  534): Console: SyntaxError: Parse error http://localhost:8000/atc_demo_ui/:498
E/browser (  534): Console: ReferenceError: Can't find variable: React http://localhost:8000/atc_demo_ui/:2
```

**Closed** 2015-06-18 00:18 UTC
Labels: atc_demo_ui, bug
