### ISSUE TITLE
internet is not working required help

### ISSUE THREAD

**Issue by asanyal902** [facebook/augmented-traffic-control#106] opened 2015-05-06 18:04 UTC
firstly ty for the urgent and helpful replies

our team has divided the work in 2 phases

1) 1st phase, using linux box (ubuntu) on which atc is configured and making hotspot on the same machine is working absolutely fine

2) now moving with phase 2, in which atc setup on the same linux box(ubuntu), now instead of making hotspot, we have our own wifi network in our office, so trying to set up at it

*** so the problem come across here "em1 interface" is connected to ethernet (linux box), the wlan0 whose is connected to the corporate wifi, and corporate wifi default gateway is the ip address of "wlan0 interface" so tht any device who is connected to the same network ip will be visible.

now started everything, device ip are visible to atc, but the problem is now internet is not working on devices nor atc, we can select the profile but no use...

can anybody help in this matter, is the setup is wrong

thank u so much

**Comment by zfjagann** [comment] 2015-05-06 21:41
Can you provide more details please.

Did you try to shape any of the clients? If so, what shaping options did you provide, and how did you provide them?

What is the default gateway on the ATC host? And also on one of the hosts that isn't working?

**Comment by ankit-ankuagrawal** [comment] 2015-05-06 22:04
interface em1 wired 
ip: 10.104.27.40
default gateway: 10.104.21.31

wlan0: 10.104.32.133
default gateway: 10.104.32.133

and device ip: 10.104.32.135
default gateway: 10.104.32.133

the profile selected is 2g, but role played by profile will be later. first the internet is not working

the problem was thinking may be the iptables may not configured, but configured them still nothing

thanking u for the response

**Comment by zfjagann** [comment] 2015-05-06 23:48
My guess is that this is caused by your default gateway for wlan0, which is itself. You should change it to 10.104.21.31. Does that sound right?
If that doesn't help it's likely an issue with your iptables settings.

**Comment by chantra** [comment] 2015-05-07 04:01
Hi @ankit-ankuagrawal 
As @zfjagann mentioned  you should only  have 1 default gateway on the atc  box and that is the one to the wired network. After removing the extraneous  gateway  and if that still does not work, can you create a gist with the output of:
* iptables-save
* ip  r
* ip a

**Comment by ankit-ankuagrawal** [comment] 2015-05-07 17:57
![setup](https://cloud.githubusercontent.com/assets/11455759/7522074/6c1cb88c-f510-11e4-8d11-61b26414932f.png)

**Comment by ankit-ankuagrawal** [comment] 2015-05-11 09:46
@chantra any update on this...

**Comment by chantra** [comment] 2015-05-11 15:32
Hi,
So your iptables settings seem totally wrong and not in sync with your ip settings. This is pretty much unrelated to atc and you should make sure that you have a working router. Also you may want to start with some minimal iptables rules and work from there.
There is plenty of resources on the internet to help you setting up a router for your favorite distribution.

I am happy to help you on irc (#atcd on freenode) which may be a better channel to help you with this. For more, this issue is not an atc issue so I will close it.

**Comment by chantra** [comment] 2015-05-11 15:38
Assuming the rest of your iptables is correct, replace 10.42.0.0/24 with 10.104.32.0/24 and you may be set.

**Comment by ankit-ankuagrawal** [comment] 2015-05-11 17:36
@chantra ty for the reply, i couldnt find irc (#atcd on freenode)...

can u pls help me

**Comment by chantra** [comment] 2015-05-11 17:38
@ankit-ankuagrawal http://facebook.github.io/augmented-traffic-control/docs/support.html

**Closed by chantra** 2015-05-11 17:38 UTC
